---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobench
  template:
    metadata:
      labels:
        app: gobench
    spec:
      containers:
      - name: gobench
        image: tnosaj/gobench
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: gobench
              key: user
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: gobench
              key: password
        - name: DBHOSTNAME
          valueFrom:
            secretKeyRef:
              name: gobench
              key: hostname
        - name: DBNAME
          value: "sbtest"
        - name: DBPORT
          value: "3306"
        - name: DBENGINE
          value: "mysql"
        ports:
        - name: web
          containerPort: 8080
      - name: prometheus
        image: prom/prometheus
        ports:
        - name: prom
          containerPort: 9090
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
