services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - 8081
  gobench:
    image: tnosaj/gobench:latest
    container_name: gobench
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - DBUSER=admin
      - DBPASSWORD=admin
      - DBHOSTNAME=172.18.0.1
      - DBPORT=9042
      - DBNAME=sbtest 
      - DBENGINE=cassandra
      - CACHE=memory:none
    volumes:
      - gobench_data:/gobenchdata
volumes:
  prom_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: prometheus_data
  gobench_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: gobench_data

