---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
  - port: 9000
    name: minio
    protocol: TCP
  - port: 9001
    name: minio-console
    protocol: TCP
  selector:
    app: minio
